# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ronan Fraser
email: Ronan@fraser.net.nz
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Ronan Fraser. Come on in, have a look around!
twitter_username: rfkfraser
github_username: username
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ronan Fraser"
  avatar : "/assets/images/bio-photo.webp"
  bio    : "I like making things that work well and look good. Seasoned atom and bit wrangler."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ronan@fraser.net.nz"
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/RFKFraser"
    - label: "CV"
      icon: "fas fa-fw fa-file"
      url: "/assets/Files/Ronan Fraser - CV - June 2025.pdf"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ronan-fraser/"

footer:
  links:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ronan@fraser.net.nz"
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/RFKFraser"
    - label: "CV"
      icon: "fas fa-fw fa-file"
      url: "/assets/files/Ronan-Fraser-CV.pdf"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ronan-fraser/"


defaults:
  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
